### ISSUE TITLE
Improve rustdoc

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/serde-yaml#10]
There is almost nothing useful at https://dtolnay.github.io/serde-yaml/. Copy over the readme examples and add at least one example for every function.

**Comment by killercup** [comment]
I was using this crate recently and noticed how its docs were not as awesome as serde_json, _but_ could probably be very similar to those of serde_json. I'll try to update some code to serde 1.0 later, and maybe also have time to add some docs here.

**Comment by Zteve** [comment]
In particular could you document how a tuple-struct is derive-serialised?
