### ISSUE TITLE
Does this crate support comments?

### ISSUE THREAD

**Issue by SirWindfield** [dtolnay/serde-yaml#100]
I am looking for a serde library that can persist comments in a config file and only change the values that have actually been changed (or re-write comments to the config file if a value changes).

Does this yaml implementation has this feature?

**Comment by dtolnay** [comment]
This crate does not. I don't know of a YAML library for Rust that is designed for modifying files. For TOML there is [`tomllib`](https://github.com/joelself/tomllib) -- you may need to look at how they do it and build a YAML library based on their approach.
