### ISSUE TITLE
`serde_yaml::to_fmt`

### ISSUE THREAD

**Issue by dpc** [dtolnay/serde-yaml#103]
It seems to me that yaml serialization always produce a valid UTF-8, so it should be possible to write it to `fmt::Formatter`. This is handy, eg for implementing `fmt::Display` as `serde_yaml` output.

**Comment by dtolnay** [comment]
I would prefer not to add a top-level entry point for this. The `Display` impl can be done like this:

```rust
impl Display for S {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        let yaml = serde_yaml::to_string(self).unwrap();
        formatter.write_str(&yaml)
    }
}
```

**Comment by dpc** [comment]
But that... allocates. :)

**Comment by dtolnay** [comment]
Can't tell if joking, but writing directly to a Formatter without allocation is likely to be slower. See:

```rust
#![feature(test)]

extern crate test;
use self::test::Bencher;

use std::fmt::{self, Display};

#[bench]
fn bench_a(b: &mut Bencher) {
    struct A;

    impl Display for A {
        fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            for _ in 0..1000 {
                formatter.write_str("a")?;
                formatter.write_str(": ")?;
                formatter.write_str("0\n")?;
            }
            Ok(())
        }
    }

    b.iter(|| A.to_string());
}

#[bench]
fn bench_b(b: &mut Bencher) {
    struct B;

    impl Display for B {
        fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            let mut s = String::new();
            for _ in 0..1000 {
                s.push_str("a");
                s.push_str(": ");
                s.push_str("0\n");
            }
            formatter.write_str(&s)
        }
    }

    b.iter(|| B.to_string());
}
```

```console
running 2 tests
test bench_a ... bench:      19,744 ns/iter (+/- 192)
test bench_b ... bench:      14,567 ns/iter (+/- 142)
```

**Comment by dpc** [comment]
Maybe what I actually wanted to ask was to be able to serialize to `std::fmt::Write` (which `std::fmt::Formatter` and `String` implement).

In some scenarios, this allocation could mater. Eg. the caller does hard real-time, or is afraid of memory fragmentation issues, and wants to use a pre-allocated buffer or something. But would they use yaml then... I guess not.

I realize this is quite an obscure requirement/use case. I think I had one more reason to ask for it (logging API that for `no_std` reason also wanted `std::fmt::Write/Formatter` or something. But I now forgot.

If it's not something that could trivially be supported, then I guess it's not worth the time. Sorry for bothering you. :)
