### ISSUE TITLE
Support i128 and u128

### ISSUE THREAD

**Issue by asomers** [dtolnay/serde-yaml#108]
It would be great if serde_yaml could support `u128` and `i128`.  I'm working on a PR and I've got it mostly working.  However, the code would be much simpler if it didn't have to support compiler versions < 1.26.0.  Are you ok with abandoning old compilers?  It's not a blocker if you aren't, but it does complicate things.

**Comment by dtolnay** [comment]
Thanks for the upcoming PR! I would like to continue to support the same range of compiler versions.

**Comment by asomers** [comment]
Ok.  In that case `i128` support will be contingent on the consumer using a newer compiler and gated by a feature flag, just like in the bincode crate.
