### ISSUE TITLE
parsing results in panick at Result::unwrap_err()

### ISSUE THREAD

**Issue by letmeloveU** [dtolnay/serde-yaml#118]
Hi,
During a recent fuzz campaign, i found that the following results in a panick:
`fn main () {
    let y = "0000: 000000000000
-000000000/000: >";
    println!("{}", serde_yaml::from_str::<serde_yaml::Value>(y).unwrap_err());
}`

`thread 'main' panicked at 'called `Result::unwrap_err()` on an `Ok` value: Mapping(Mapping { map: {Number(PosInt(0)): Number(PosInt(0)), String("-000000000/000"): String("")} })', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap_err
             at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libcore/result.rs:867
  10: test::main
             at ./test.rs:6
  11: std::rt::lang_start::{{closure}}
             at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:398
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /rustc/f1e2fa8f0469aac1ea69dd5b6164e1d198d57934/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start`

**Comment by dtolnay** [comment]
Your code is doing:

```rust
serde_yaml::from_str::<Value>(y).unwrap_err()
```

where `y` is a string containing the following data:

```yaml
0000: 000000000000
-000000000/000: >
```

That is a valid YAML document, so serde_yaml successfully parses it and returns Ok. I believe this is the correct behavior.
