### ISSUE TITLE
Missing support for Default trait

### ISSUE THREAD

**Issue by macisamuele** [dtolnay/serde-yaml#119]
Would be nice if serde-yaml would allow the following: `serde_yaml::Value::default()`.

This is currently a partial blocker for a personal project I'm working on.

I would ask if there are objections on allowing a default value for serde-yaml like is done on serde-json.

My suggestion would be to use `Value::Null` as default value

**Comment by dtolnay** [comment]
I would accept a PR to add a Default impl.

**Comment by macisamuele** [comment]
@dtolnay thanks a lot for the immediate response 😄 
I had a local branch that I was using to validate if the default requirement was needed or there were easy/nice way to workaround the issue.

By defining a default value, my project would be much simplified and this library would get the handling of default for structs deserialization
