### ISSUE TITLE
Allow matching ErrorImpl

### ISSUE THREAD

**Issue by sthesing** [dtolnay/serde-yaml#121]
I'd like to be able to handle different errors. However, I can't match `ErrorImpl`, because  `serde_yaml::error` is private. Is there a way to expose it?

**Comment by dtolnay** [comment]
Which error cases do you need to be able to handle differently?

We keep the error details private because we occasionally need to add or remove error variants as the implementation evolves.

**Comment by sthesing** [comment]
In my case, it is the `Message` and the `MoreThanOneDocument` variants.

I deal with markdown documents that have a yaml-metadata block (as defined by [pandoc](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block)).
Pure Markdown files without such a block cause a `Message`-error.
Others that end their metadata block not with `...` but with `---`, or that contain another yaml-block in the document body cause a `MoreThanOneDocument`-error.
I'd like to handle these cases differently.

**Comment by dtolnay** [comment]
I would recommend implementing those structural checks using [yaml-rust](https://github.com/chyh1990/yaml-rust) directly. After the `---` and `...` are determined to be correct you can deserialize the content with serde_yaml.

**Comment by sthesing** [comment]
OK. A pity, but I understand.
Will insert some preparatory code that ensures that only unproblematic yaml is passed to serde_yaml.
Thanks.
