### ISSUE TITLE
Get error message

### ISSUE THREAD

**Issue by bubulemaster** [dtolnay/serde-yaml#125]
Hi,

If a field is missing, I can know by using `println!("{:?}, err)`.

But if I just want message (not location) I can't.

Are you agree to create a PR `pub fn message()` in Error ?

Thanks

**Comment by dtolnay** [comment]
I would consider a PR adding a `message` method which does not include the error location.

What do you need this for?

**Comment by bubulemaster** [comment]
You're right.

I want display a message with my formatter.

I'm write a cli-tool and I want change format of default display message:
```
Message("missing field `download_filename`", Some(Pos { marker: Marker { index: 10, line: 1, col: 10 }, path: "." }))
```

**Comment by dtolnay** [comment]
That is not the default display representation, it is the Debug representation. Does the Display representation work for your use case?

**Comment by bubulemaster** [comment]
Ok, sorry.

Display representation is nice.
