### ISSUE TITLE
Key as value name

### ISSUE THREAD

**Issue by silvio** [dtolnay/serde-yaml#126]
Hi, I have a question about [serde_yaml]. I want to have a yaml file where the keys not known at compile time, therefore I cannot create a `struct` for this file. Something like this:

~~~yaml
"string":
    - blah: 1
"string2":
    - blah: 2
~~~

`String` and `string2` are not known at compile time of my application. If I run my programm I get failures like this (and other):

~~~error
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Scan(ScanError { mark: Marker { index: 441, line: 22, col: 16 }, info: "mapping values are not allowed in this context" })'
~~~

Is this possible with serde-yaml or even with yaml?

[serde_yaml]: https://docs.rs/serde_yaml/0.8.8/serde_yaml

**Comment by dtolnay** [comment]
If you need to deserialize key-value data in which the keys are not known at compile time, you would need to deserialize it into something like a HashMap\<String, T\> rather than a struct.

Separately, according to the error you posted, your input file is not valid YAML syntax on line 22.

**Comment by silvio** [comment]
Thanks @dtolnay , this has worked. It came not in my mind to use a HashMap!
