### ISSUE TITLE
Implement From<serde_yaml::Error> for io::Error

### ISSUE THREAD

**Issue by TomCrypto** [dtolnay/serde-yaml#127]
Basically the opposite of #97, this would be quite handy to avoid needing a `map_err` when e.g. you're reading YAML configuration from a file on startup and want to get some error out to the user.

serde_json has this here https://docs.serde.rs/src/serde_json/error.rs.html#134-173

**Comment by dtolnay** [comment]
Thanks, I would accept a PR for this to match what exists in serde_json.

**Comment by dtolnay** [comment]
I'll give this a close since it hasn't been important enough to anyone to send a PR.
