### ISSUE TITLE
Octal literal is deserialized as decimal

### ISSUE THREAD

**Issue by isegal** [dtolnay/serde-yaml#134]
When passing an octal number as per specification at https://yaml.org/refcard.html
The value does not get parsed as octal.

Ex:
```
#[test]
fn test_octal_deserialize() {
    let source = r#"
---
value: 0755
"#;
    #[derive(Serialize, Deserialize, PartialEq, Debug)]
    struct TestOctal {
        value: u32,
    }
    let result: TestOctal = serde_yaml::from_str(&source).unwrap();
    assert_eq!(result, TestOctal{
        value: 0o755
    });
}
```

Expected :TestOctal { value: 493 }
Actual   :TestOctal { value: 755 }

**Comment by dtolnay** [comment]
That link describes yaml 1.1. This library implements yaml 1.2 which uses `0o` prefix for octal.

```yaml
---
value: 0o755
```

**Comment by isegal** [comment]
Just tested with 0o prefix. Works as expected. Thank you.
