### ISSUE TITLE
Remove all the PartialEq<Value> impls for standard library types

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/serde-yaml#140]
Currently we have:

- impl PartialEq\<Value\> for str
- impl PartialEq\<Value\> for &str
- impl PartialEq\<Value\> for String
- impl PartialEq\<Value\> for i8
- impl PartialEq\<Value\> for i16
- impl PartialEq\<Value\> for i32
- impl PartialEq\<Value\> for i64
- impl PartialEq\<Value\> for isize
- impl PartialEq\<Value\> for u8
- impl PartialEq\<Value\> for u16
- impl PartialEq\<Value\> for u32
- impl PartialEq\<Value\> for u64
- impl PartialEq\<Value\> for usize
- impl PartialEq\<Value\> for f32
- impl PartialEq\<Value\> for f64

These potentially lead to surprising inference errors in code that is unrelated to Serde: https://github.com/serde-rs/json/issues/357, https://github.com/rust-lang/rust/issues/46257

**Comment by ejpcmac** [comment]
Hello @dtolnay, I’ve come across some very strange type inference issues after adding a completely unrelated dependency to one of my projects, and just narrowed it down to `serde_yaml`. I have a minimal working example if it is helpful.
