### ISSUE TITLE
Control output formatting to omit `---`

### ISSUE THREAD

**Issue by keirlawson** [dtolnay/serde-yaml#141]
I couldn't see any mention of this in the docs, is it possible to control exactly how serialized YAML is formatted by serde-yaml? I'd like to be able to omit the `---` at the start for example or control indentation (in places where it does not effect semantics)

**Comment by dtolnay** [comment]
AFAIK this is not supported by https://github.com/chyh1990/yaml-rust. It would need to be implemented there, or we would need to move to different yaml backend (with the latter option being much preferred, for many reasons).

**Comment by cfrantz** [comment]
> AFAIK this is not supported by https://github.com/chyh1990/yaml-rust. It would need to be implemented there, or we would need to move to different yaml backend (with the latter option being much preferred, for many reasons).

Could you comment on the reasons you'd prefer a different yaml backend, whether you have any specific alternatives in mind or what you'd like to see in a alternative yaml backend from a design or features standpoint?  I would also like to have more control over output formatting (see #235) and have some as-yet uncommitted changes to yaml-rust, but if there are already ideas for a different backend, I'd rather spend my efforts there.

**Comment by dtolnay** [comment]
As of 0.9, the leading `---\n` is omitted by default, so I'll close this since that was OP's motivation for the issue. If other users want other formatting options those should be filed individually.
