### ISSUE TITLE
[Question/Feature Request] Keep arrays on serializing?

### ISSUE THREAD

**Issue by Geobert** [dtolnay/serde-yaml#143]
Hi,

I have in a file:
```yaml
tags: [tag1, tag2]
```
It deserialized into a `Vec<String>` but when it serialize it back we got:
```yaml
tags:
    - tag1
    - tag2
```

Is there a way to keep the first version on serializing? If not, can we have a field attribute to say so?

**Comment by sanboxrunner** [comment]
I'd like to also ask for this! The former can be a lot more compact, and YAML is frequently used for human-readable save files.

**Comment by christianpoveda** [comment]
I'm under the impression this is actually a `yaml_rust` issue but I'm no expert to judge. I think this is the related code: https://github.com/chyh1990/yaml-rust/blob/master/src/emitter.rs#L196

**Comment by dtolnay** [comment]
I'll close and track this under #141. This would like happen only as part of switching off of yaml-rust as the yaml backend.

**Comment by nkconnor** [comment]
This could be re-opened since it looks like #141 is closed for different reasons. From a quick scan of `yaml-rust`, I don't see a feature request for this functionality.

**Comment by nyurik** [comment]
Per #141, re-creating this issue as #402
