### ISSUE TITLE
Adding comments

### ISSUE THREAD

**Issue by clintnetwork** [dtolnay/serde-yaml#145]
Hi,

I would like to know if it's possible to add comments to the YAML output?

Thank you!

**Comment by clintnetwork** [comment]
Related to https://github.com/lucid-kv/lucid/issues/22

**Comment by clintnetwork** [comment]
@dtolnay 😁

**Comment by dtolnay** [comment]
This is not supported. You would need to use a different yaml library or some kind of postprocessor to insert the comments.

**Comment by clintnetwork** [comment]
Hey,

Could you add it? :D

**Comment by dtolnay** [comment]
No, I don't think it's a good fit for this library.

**Comment by clintnetwork** [comment]
Okey no problem!
