### ISSUE TITLE
Way to Optionally Serialize `Option<T>` as Nothing, i.e. Not Present in Output

### ISSUE THREAD

**Issue by zicklag** [dtolnay/serde-yaml#146]
I would like to be able to serialize a `None` value in Rust as the field not existing in the output YAML. The application that uses the YAML that I am serializing doesn't like the `~` to represent the absence of a field.

In the meantime I'm probably just going to use Regex to remove all of the fields that are set to `~`. I'm not 100% sure that this isn't rather something that the application I'm using should handle as opposed to this library.

**Comment by hexane360** [comment]
You can use the `skip_serializing_if` serde field attribute, as described [here](https://serde.rs/field-attrs.html#skip_serializing_if).

```
#[serde(skip_serializing_if = "Option::is_none")]
field: Option<f64>
```

**Comment by zicklag** [comment]
Oh, that's perfect, thanks.
