### ISSUE TITLE
to_writer seems to be unacceptably slow on lustre fs

### ISSUE THREAD

**Issue by astrojhgu** [dtolnay/serde-yaml#148]
The mounting parameter of the fs is 
```
 /home type lustre (rw,noatime,flock,lazystatfs)
```

When I use `to_writer` to write data to disk, the operation can block for a very long time (e.g., 100 kB/minute).

If I first dump the data into a string by using `to_string` then use `writeln!` to write data actually to disk, the behavior is normal.

```
serde = {version = "1.0", features=["derive"]}
serde_yaml = "0.8.11"
```

**Comment by dtolnay** [comment]
This is normal, that's just how slow unbuffered writes are. If your data fits in memory then emitting it all at once is always going to be fastest. If not, you would need to use a buffered writer like https://doc.rust-lang.org/std/io/struct.BufWriter.html.
