### ISSUE TITLE
Parsing a unit enum value as a String rather than a HashMap

### ISSUE THREAD

**Issue by Lindenk** [dtolnay/serde-yaml#15]
Currently, when parsing an enum type, any Values must be a HashMap:

`main.rs`:
```rust
#![feature(custom_derive, plugin)]
#![plugin(serde_macros)]

#[macro_use]
extern crate serde;
extern crate serde_yaml;

use std::fs::File;


#[derive(Serialize, Deserialize, Debug)]
enum Beans {
    Blue,
    Black,
    Chamomile
}

#[derive(Serialize, Deserialize, Debug)]
struct Food {
    beans : Beans
}

fn main() {
    let f = File::open("test_yaml.yaml").unwrap();
    let test : Food = serde_yaml::from_reader(f).unwrap();
    
    println!("{:?}", test);
}
```

`test_yaml.yaml`:
```yaml
beans:
    Blue: ()
```

This would will parse `Blue` into `test`. However, it is inconvenient to require all unit enum values to have associated non-existent data. Instead, if the value is a unit value, it should also be parsable as a string.

```yaml
beans: Blue
```

**Comment by dtolnay** [comment]
Thanks for the PR but the party line from Serde has been that this decision should be made by the individual data types, not the serialization format (YAML, JSON, etc). If your data type should be represented as a string, that should be reflected in the Serialize/Deserialize impl for the type.

The issue of making it possible to derive Serialize/Deserialize for enums that are represented as strings is tracked at https://github.com/serde-rs/serde/issues/251. Consider implementing `#[serde(serialize_as_string)]` as suggested in that thread - we would welcome a serde PR.
