### ISSUE TITLE
Error path information lost for internally tagged enums

### ISSUE THREAD

**Issue by nthuemmel** [dtolnay/serde-yaml#151]
When attempting to deserialize an internally tagged enum, which fails due to some nested component,  the resulting error does not contain path or line/column information. I would expect the path information to be preserved, as it is for externally tagged enums or other types.

This is shown by the following example (a slightly modified variant of one of serde_yaml's test cases):

```rust
fn test_error<T>(yaml: &str, expected: &str)
where
    T: serde::de::DeserializeOwned + Debug,
{
    let result = serde_yaml::from_str::<T>(yaml);
    assert_eq!(expected, format!("{}", result.unwrap_err()));
}

#[test]
fn test_incorrect_nested_type() {
    #[derive(Deserialize, Debug)]
    #[serde(tag = "version")]
    enum A {
        version2 { b: Vec<B> },
    }
    #[derive(Deserialize, Debug)]
    enum B {
        C(C),
    }
    #[derive(Deserialize, Debug)]
    struct C {
        d: bool,
    }
    let yaml = "
---
version: \"version2\"
b:
  - C:
      d: fase
";
    let expected =
        "b[0].C.d: invalid type: string \"fase\", expected a boolean at line 4 column 10";
    test_error::<A>(&yaml, expected);
}
```

Actual output: `invalid type: string "fase", expected a boolean`

Tested with serde_yaml 0.8.11, serde 1.0.105

**Comment by dtolnay** [comment]
Closing in favor of tracking this as part of #153, which is a newer issue but has some relevant investigation and is apparently the one that search engines prefer.
