### ISSUE TITLE
Results can differ when deserializing directly from text vs deserializing from Value from text

### ISSUE THREAD

**Issue by wfraser** [dtolnay/serde-yaml#170]
The example I ran into is if you have an enum with a variant name that's a number. If you deserialize straight from text, serde-yaml is smart enough to recognize the number and do the right thing. But if you deserialize into a `Value` first, and then into the custom type, it chokes when it sees an integer where it expected a string.

I ran into this because I'm using `yaml_merge_keys` to implement `<<:` reference merges, so I'm using serde-yaml to get an unstructured Value first, running yaml_merge_keys on that, and then handing it back to serde-yaml to do the rest of the parsing. This works great, until you have an enum variant that's a number.

Working code example:

```rust
extern crate serde;
extern crate serde_yaml;

use serde::Deserialize;
use serde_yaml::Value;

#[derive(Debug, Deserialize, PartialEq)]
enum Enum {
    #[serde(rename="42")]
    FortyTwo(String),
}

fn main() {
    let yaml = r#"42: foobar"#;

    let expected = Enum::FortyTwo("foobar".to_owned());
    
    // Parsing it directly from text works.
    assert_eq!(expected, serde_yaml::from_str::<Enum>(yaml).unwrap());
    
    // Parsing it to an unstructured Value and then into the type fails because "42" is an integer.
    assert_eq!(expected, serde_yaml::from_str::<Value>(yaml).and_then(serde_yaml::from_value::<Enum>).unwrap());
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cb2c38e108fbe1a35a3439ad3602c85e))

Errors:

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.97s
     Running `target/debug/playground`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Message("invalid type: integer `42`, expected variant identifier", None)', src/main.rs:22:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by dtolnay** [comment]
I believe it's inevitable that deserializing directly from text can be different from deserializing Value as an intermediate step. The deserialization from text to `Value` is inherently lossy.

RawValue (#173) may be a more appropriate intermediate step for what you described.
