### ISSUE TITLE
Support serialization of strings to literal and folded scalars

### ISSUE THREAD

**Issue by spenserblack** [dtolnay/serde-yaml#174]
Apologies if this feature already exists, but I didn't see it in the documentation.

## Info

[the literal scalar `|`](https://yaml.org/spec/1.2/spec.html#|%20literal%20style//) can be used in YAML to break up a string to multiple lines, treating the line breaks literally.

[the folded scalar `>`](https://yaml.org/spec/1.2/spec.html#%3E%20folded%20style//) also can be used to break up a string into multiple lines, but it treats line breaks as spaces.

## Request

When serializing a value containing a multiline string, it seems to always serialize that string to a single line with line breaks represented as `\n` ([reproduction](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=use%20serde%3A%3ASerialize%3B%0Ause%20serde_yaml%3A%3Ato_string%3B%0A%0Aconst%20MULTILINE%3A%20%26str%20%3D%20%22%5C%0AA%20string%0Awith%0Amultiple%20lines%0A%22%3B%0A%0A%23%5Bderive(Debug%2C%20Serialize)%5D%0Astruct%20Foo%3C'a%3E%20%7B%0A%20%20%20%20bar%3A%20%26'a%20str%2C%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20let%20value%20%3D%20Foo%20%7B%20bar%3A%20MULTILINE%20%7D%3B%0A%20%20%20%20%0A%20%20%20%20let%20yaml%20%3D%20to_string(%26value)%3B%0A%20%20%20%20%0A%20%20%20%20println!(%22%7B%3A%23%3F%7D%20as%20YAML%3A%20%7B%3A%3F%7D%22%2C%20value%2C%20yaml)%3B%0A%7D))
I think that there should be some way to specify *how* you want your string to be serialized (single line, folded scalar, literal scalar).

#### Input
```yaml
key: |
  line 1
  line 2
```
#### Output (JSON)
```json
{ "key": "line 1\nline 2\n" }
```

#### Input
```yaml
key: >
  word1
  word2
```
#### Output (JSON)
```json
{ "key": "word1 word2" }
```

**Comment by emmanueltouzery** [comment]
I'm also interested in this feature, and several others, but this would have to be implemented by the underlying library used by serde-yaml.

Currently, that is [yaml-rust](https://github.com/chyh1990/yaml-rust), which is not really maintained. There are three unanswered pull requests for yaml-rust to add the feature:
* https://github.com/chyh1990/yaml-rust/pull/137
* https://github.com/chyh1990/yaml-rust/pull/136
* https://github.com/chyh1990/yaml-rust/pull/132

There isn't much that can be done from serde-yaml I'm afraid.

**Comment by spenserblack** [comment]
I see... I was worried that that was the case 😞  

Hopefully when those PRs are addressed or a fork is created, this issue can be addressed.

Thanks for your answer!

**Comment by jhoobergs** [comment]
@dtolnay Is this something that you would want in this library? Or should I use my own fork(s) if I want this? The main problem does lay at https://github.com/chyh1990/yaml-rust I guess?

**Comment by dtolnay** [comment]
To the extent that this issue is asking to expose *choice* over the string representation at the granularity of individual fields, that is not something I would accept in this library.

If it is asking just for prettier defaults, such as serializing to literal scalar if a string value contains newlines, I am open to that but this crate is not where that code lives.

**Comment by jhoobergs** [comment]
@dtolnay `yaml-rust` doesn't seem so active. Where do you stand on using an on-crates-published-fork (like https://github.com/davvid/yaml-rust)  which implements these prettier defaults? (it basically equals `yaml-rust` but with https://github.com/chyh1990/yaml-rust/pull/137 merged and working CI)

**Comment by dtolnay** [comment]
I wouldn't do that. It would be good to drop the dependency on yaml-rust entirely though, in favor of the backend style described in https://github.com/dtolnay/request-for-implementation/issues/9.

**Comment by spenserblack** [comment]
>If it is asking just for prettier defaults, such as serializing to literal scalar if a string value contains newlines

That is actually what I initially wanted, but was worried that it was too opinionated :laughing: 

>this crate is not where that code lives.

If/when possible, could this issue be transferred to the relevant repo?
