### ISSUE TITLE
Deserialize Error 128 bit hex number

### ISSUE THREAD

**Issue by Maeda-Naoki** [dtolnay/serde-yaml#196]
I can't deserialize 128 bit hex number.
The error message shows "invalid type: string".
I expect to recognize it as a number.

Error message
>thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Message("invalid type: string \"0x1234567890ABCDEF1234567890ABCDEF\", expected u128", Some(Pos { marker: Marker { index: 7, line: 2, col: 3 }, path: "x" }))', src/main.rs:15:57

```rust
use serde::Deserialize;
use indoc::indoc;

#[derive(Debug, Deserialize)]
struct Data {
    x: u128
}

fn main() {
    let yaml = indoc! {"
        ---
        x: 0x1234567890ABCDEF1234567890ABCDEF
    "};

    // ★Deserialize error
    let deserialized: Data = serde_yaml::from_str(yaml).unwrap();
}

```

**Comment by dtolnay** [comment]
This is fixed in 0.9.

```console
[src/main.rs:17] deserialized = Data {
    x: 24197857200151252728969465429440056815,
}
```
