### ISSUE TITLE
How to serialize numbers in different bases?

### ISSUE THREAD

**Issue by asomers** [dtolnay/serde-yaml#198]
YAML can represent numbers as decimal, hexadecimal, or octal.  serde-yaml can deserialize all three.  But how can I select which to use when serializing numbers?  As far as I can tell, serde-yaml always uses decimal.  The only thing I can do is to transform my number to a string, i.e. with `format!({:#x}, x)` and serialize that.  However, that causes serde-yaml to add quotes, meaning it will only deserialize as a string, not as a number.

Give a struct like
```rust
struct Foo {
    x: u32,
    m: u32
}
let foo = Foo {x: 0xdeadbeef, m: 0o755};
```
I want to be able to serialize it and get the following:
```yaml
Foo:
  x: 0xdeadbeef
  y: 0o755
```

**Comment by dtolnay** [comment]
I do not consider this to be in scope for this library.
