### ISSUE TITLE
serde_yaml::to_string adds characters not present in the original string

### ISSUE THREAD

**Issue by cloudultima3164** [dtolnay/serde-yaml#200]
I just noticed I was getting some errors when using `serde_yaml::to_string()` in that it adds some characters on the beginning and end of the string when converting from a Value object.

This is the basic flow of my program up to the point when I use the to_string function. The program is making requests using Hyper.

```rust

use hyper::{
    Client,
    Method,
    Request,
    Response,
    body::{self, Body, Bytes},
};
use std::time::Duration;

async fn print_conversion_result(query: String) -> Result<()> {
    let client = Client::new()
    let req = Request::builder()
                        .method(Method::POST)
                        .uri(&uri)
                        .header("Content-Type","application/json")
                        .body(Body::from(query))?;
    
    let mut response: Response<Body> = self.client().request(req).await?;
    let resp_body: Option<Bytes> = Some(body::to_bytes(response.body_mut()).await?);
    let yaml_resp: serde_yaml::Value = serde_yaml::from_slice(&*(resp_body.take().unwrap()))?;
    let map_data: Mapping = yaml_data.as_mapping_mut().unwrap();
    let ret_string: Option<Value> = map_data.remove(&"cursor".into()); 
    // the above is what I am sending in the next request to get more results, but it needs to be converted to a string first
    
    match ret_string {
        Some(c) => { 
            println!("Using as_str: {:?}", c.clone().as_str().unwrap());
            println!("Using serde_yaml::to_string: {:?}", serde_yaml::to_string(&c)?);
        },
        None => ()
    }
    Ok(())
}
```

I printed the result of conversion as shown at the end of my code to check what was happening, and found that `as_str()` gives the expected result, while `serde_yaml::to_string()` adds some characters on the beginning and end of the string, which was causing errors.

Here is the result of that (omitting most of the string):
```shell
Using as_str: "16euAwFaAXNA[...]eHQAAAABHw=="
Using serde_yaml::to_string: "---\n16euAwFaAXNA[...]eHQAAAABHw==\n"
```

And here is what the key and value returned to me by the api actually looks like (omitted in the same way as previously):
```yaml
cursor: 16euAwFaAXNA[...]eHQAAAABHw==
```

Is it expected that `serde_yaml::to_string()` adds characters like this during conversion?

**Comment by dtolnay** [comment]
Yes, I think this is behaving correctly. The serialized YAML representation of a string is not identical to the unserialized string.
