### ISSUE TITLE
serde_yaml::Hash unusable if floats are present in map _value_ positions.

### ISSUE THREAD

**Issue by Fuuzetsu** [dtolnay/serde-yaml#204]
These two maps, when turned to serde_yaml::Value give the same hashes:

```yaml
foo: 1.2
```

```yaml
foo: 8.7
```

The reason is the Hash instance of Number:

```rust
#[allow(clippy::derive_hash_xor_eq)]
impl Hash for Number {
    fn hash<H: Hasher>(&self, state: &mut H) {
        match self.n {
            N::Float(_) => {
                // you should feel bad for using f64 as a map key
                3.hash(state)
            }
            N::PosInt(u) => u.hash(state),
            N::NegInt(i) => i.hash(state),
        }
    }
}
```

It gives constant values for `f64`. The comment tries to shame the user about using floats as keys. Sadly, it completely forgets that `Number` can be used elsewhere. In this case, we have:

```rust
#[derive(Clone, Debug, Default, Eq, Hash, PartialEq, PartialOrd)]
pub struct Mapping {
    map: LinkedHashMap<Value, Value>,
}
```

The `Hash` for the `LinkedHashMap` just hashes the `(key, value)` values.

This means that when `value` is `N::Float`, the hash doesn't change when the value does. This makes it pretty much unfit for purpose...

**Comment by Fuuzetsu** [comment]
As for the question about what to do about it, I guess there are few options.

* Remove `Hash` implementation all together.
* Turn the `f64` into bytes and hash as-is ala Haskell, letting the user deal with NaN issues (https://hackage.haskell.org/package/hashable-1.3.2.0/docs/src/Data.Hashable.Class.html#line-554)
* Panic on NaN values (kind of like in https://github.com/dtolnay/serde-yaml/issues/107 but actually check for NaN)

I guess our workaround will be to hash the `serde_yaml::to_string` or something for now.

**Comment by dtolnay** [comment]
This is intentional. Floats are not supposed to be used on the key side of a map (whether nested inside another object or not).

**Comment by Fuuzetsu** [comment]
> This is intentional. Floats are not supposed to be used on the key side of a map (whether nested inside another object or not).

Please re-read the issue and re-open. I'm not using floats on the key side of the map. I'm _only_ using them on the value side.

**Comment by Fuuzetsu** [comment]
> This is intentional. Floats are not supposed to be used on the key side of a map (whether nested inside another object or not).

By the way nowhere in the docs can I find the mention of this restriction, not on any Hash instances nor anywhere else. Maybe I missed it but it seems like something that should be documented.

Regardless, this issue isn't about map keys, it's about _any_ float value appearing anywhere.

**Comment by dtolnay** [comment]
You have some data structure that transitively contains floats. Instances of whatever data structure you have are being hashed in order to key some operation on those hashes. This is equivalent to putting a float directly in a key position.

**Comment by Fuuzetsu** [comment]
> You have some data structure that transitively contains floats. Instances of whatever data structure you have are being hashed in order to key some operation on those hashes. This is equivalent to putting a float directly in a key position.

I was using the hash as a key of files in S3: if we have the same serde_yaml::Value, there's no point uploading it twice to S3.

If you just object completely to ever hashing a `f64` then I don't see why the `Hash` instance exists at all: it's broken. At least one of the following should probably happen:

* Actually document this behaviour somewhere. It's completely not intuitive.
* Try our best to actually hash the floats.
* Remove the Hash implementation.

Clearly existing behaviour is just surprising and not documented anywhere.

**Comment by fumieval** [comment]
Please re-open this and please explain why `3` is more preferable than panic.

Also, isn't `Mapping` unsound? It is a map from Value, which may contain a float by definition. It is based on `LinkedHashMap` so it contains undocumented undefined behaviour.

Perhaps we could make a variant of `Value` which is guaranteed not to contain float?
