### ISSUE TITLE
Compatibility with rust-yaml

### ISSUE THREAD

**Issue by XAMPPRocky** [dtolnay/serde-yaml#205]
Hello, this library says that under the hood it uses `rust-yaml`, however it doesn't seem to be compatible with the library's own types for YAML documents. It would be nice if there were `From` implementations so that if I needed to use to lower-level parser (specifically I want to parse multi-document files), that I could easily convert back into `serde` compatible types.

**Comment by dtolnay** [comment]
Yaml-rust types are intentionally not present in the public API of this crate. The yaml-rust dependency is intended to be deleted as soon as possible.

**Comment by XAMPPRocky** [comment]
Oh, is there plans to support multiple documents in `serde-yaml`? That's my main motivation for wanting to use the lower level parser.

**Comment by dtolnay** [comment]
Yes, see the second code snippet in https://docs.rs/serde_yaml/0.8.17/serde_yaml/struct.Deserializer.html.

**Comment by XAMPPRocky** [comment]
Ah thanks, I thought it supported it, but couldn't find it. It would be nice if there was a way to search the docs for format specific features. Thank you for your help!
