### ISSUE TITLE
Add a `to_string_pretty` method

### ISSUE THREAD

**Issue by MarcoIeni** [dtolnay/serde-yaml#226]
I would like to be able to print in a different way `\n` inside strings.
Example:
```rust
use serde::Serialize;

#[derive(Serialize, Debug)]
struct A {
    b: String,
    c: String,
}

fn main() {
    let a = A {
        b: "aaa\nbbb\n".to_string(),
        c: "ccc".to_string(),
    };
    let yaml = serde_yaml::to_string(&a).unwrap();
    println!("{}", yaml);
}
```

prints:

```yaml
---
b: "aaa\nbbb\n"
c: ccc
```

Instead I would like to have:

```yaml
---
b: |
  aaa
  bbb
c: cccc
```

Maybe this could be a good fit for a function similar to [serde_json::to_string_pretty](https://docs.serde.rs/serde_json/fn.to_string_pretty.html)

**Comment by dtolnay** [comment]
As of 0.9 the formatting is prettier by default so a separate method shouldn't be needed.
