### ISSUE TITLE
Deserialize null value as default

### ISSUE THREAD

**Issue by vthib** [dtolnay/serde-yaml#230]
Hello, thanks for all your work on this project. I have an issue that is a bit annoying to handle and would like to discuss.
I apologize if this has already been discussed, I haven't found this exact issue in my searches.

Basically, A YAML null value is properly deserialized in an Option, but introduces errors if used in conjunction with the `#[serde(default)]`

Here is an example of what i mean:

```rust
use serde::Deserialize;

#[derive(Debug, PartialEq, Deserialize)]
struct A {
    y: i32,
    z: Option<i32>
}

#[derive(Debug, PartialEq, Deserialize)]
struct B {
    y: i32,
    #[serde(default)]
    z: i32
}

fn main() {
    // This works
    assert_eq!(serde_yaml::from_str::<A>("y: 2").unwrap(), A { y: 2, z: None });
    // This works as well
    assert_eq!(serde_yaml::from_str::<A>("y: 2\nz:").unwrap(), A { y: 2, z: None });

    // This works thanks to serde(default)
    assert_eq!(serde_yaml::from_str::<B>("y: 2").unwrap(), B { y: 2, z: 0 });
    // This fails: invalid type: unit value, expected i32
    assert_eq!(serde_yaml::from_str::<B>("y: 2\nz:").unwrap(), B { y: 2, z: 0 });
}
```

This is annoying because it means that `#[serde(default)]` cannot really be used when deserializing yaml files which origins is not controlled, as it is common for some users to have templates of all keys possible for a document, and leave `key:` when no value is needed, for example:

```
name: My yaml file
description:
metadata:
...
```

Do you feel like this is a behavior that should be fixed? And if it is, is it easy to fix? I realize this is probably more of a serde/serde-yaml cross issue, but if you agree with the issue and a fix is doable, i can try to tackle it.

**Comment by jonasbb** [comment]
One option would be to change the deserialization by applying some field attributes. This uses [`serde_with::DefaultOnNull`](https://docs.rs/serde_with/latest/serde_with/struct.DefaultOnNull.html) which turns any `null` into the `Default` value.

```rust
#[serde_with::serde_as]
#[derive(Debug, PartialEq, Deserialize)]
struct B {
    y: i32,
    #[serde_as(as = "serde_with::DefaultOnNull")]
    #[serde(default)]
    z: i32
}
```

**Comment by vthib** [comment]
Indeed, thanks for this suggestion, it works nicely. I'm closing this ticket as this ticket was intended to be a discussion on this particular issue, and the current behavior can be considered to be as expected.
