### ISSUE TITLE
Indexmap Dependency and Old rustc Versions

### ISSUE THREAD

**Issue by mitsuhiko** [dtolnay/serde-yaml#233]
It looks like indexmap (because of hashbrown) is likely going to move up to 1.56 soon (https://github.com/bluss/indexmap/issues/214 and https://github.com/rust-lang/hashbrown/issues/310). As of a few versions ago serde-yaml now requires indexmap which moves up the minimum rustc version.

Right now I got used to being able to use serde-yaml to support old rustc versions which some users of my crates are still using. Would it be an option to make this dependency optional?

**Comment by dtolnay** [comment]
Hashbrown's approach seems fine to me. In my experience almost nobody (let's say 0.5%) cares about building Rust software with anything older than the current stable, or briefly the previous stable when a new one has just come out. Certainly a lot of people run CI builds on various much older toolchains, ostensibly to support some actual user who they think wants that toolchain to work, but if you chase the chain of "this reverse dependency wanted it" to "this second-order reverse dependency wanted it" to "this third-order reverse dependency wanted it" you'll find it always bottoms out in no actual person ever building the software for real use using the old toolchain, so the whole endeavor is almost entirely a waste of everybody's time. The people pinning old toolchains are universally better served by pinning old crate versions using a lockfile anyway.

**Comment by mitsuhiko** [comment]
I suppose this means that serde-yaml is likely to move up to 1.56? Mostly trying to understand my options here.

**Comment by dtolnay** [comment]
I think so.
