### ISSUE TITLE
Incorrect line number deserializing a vector of tagged enums

### ISSUE THREAD

**Issue by ttencate** [dtolnay/serde-yaml#240]
Dependencies:

```
serde = { version = '1.0.136', features = ['derive'] }
serde_yaml = '0.8.23'
```

Code:

```
#[derive(serde::Deserialize)]
#[serde(tag = "type")]
enum Item {
    One { one: String },
    Two { two: String },
}

const INPUT: &str = "
- type: One
  one: x
- type: Two
  two: x
- type: One
  one: x
- type: Two
  one: x
- type: Two
  two: x
";

fn main() {
    if let Err(err) = serde_yaml::from_str::<Vec<Item>>(INPUT) {
        println!("{}", err);
    }
}
```

Did you spot the error in the input? `serde-yaml` did, but points at the wrong place:

```
missing field `two` at line 2 column 1
```

Expected:

```
missing field `two` at line 8 column 1
```

`serde-yaml` seems to point at the start of the list, not at the list item where the missing field is. Since my actual code has hundreds of lines of YAML with dozens of enum variants, each with about a dozen fields, this makes it hard to find where the actual error is.

**Comment by ANtlord** [comment]
The issue duplicates https://github.com/dtolnay/serde-yaml/issues/153
