### ISSUE TITLE
Remove the flush in to_writer

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/serde-yaml#29]
Added in https://github.com/dtolnay/serde-yaml/commit/5df9007714aba3c717d30e859e8feb95bc13a89c to preserve backward compatibility with 0.4.0 which always flushed the writer. We should be able to leave flushing to the caller like serde_json does.

cc @emk

**Comment by emk** [comment]
Looks great. I expect to see a real performance improvement. Thank you!

**Comment by dtolnay** [comment]
Fixed in 80d30612b5b54e1b87e1ead775ad79affa66f835.

**Comment by dtolnay** [comment]
I released [0.5.0](https://github.com/dtolnay/serde-yaml/releases/tag/0.5.0) with this change.

**Comment by emk** [comment]
I can confirm that moving flush out of the inner loop sped up cage by a
factor of 20. Thanks very much for this quick and helpful fix!
