### ISSUE TITLE
Change default multiline string representation to use `|`

### ISSUE THREAD

**Issue by banool** [dtolnay/serde-yaml#292]
It was previously stated here (https://github.com/dtolnay/serde-yaml/issues/174) that it's not the place of this crate to provide customization for how the outputted yaml should look, but it's possible that we could change the default formatting.

I suggest that if we see that a string has a newline in it, we format it with `|`.

I will take a crack at this, I'm just opening this issue to get thoughts now in case folks disagree.

**Comment by dtolnay** [comment]
This crate already uses `|` for multiline strings (or `|-` if no trailing newline).

```rust
use serde::Serialize;

#[derive(Serialize)]
struct Struct<'a> {
    first: &'a str,
    second: &'a str,
    third: &'a str,
    fourth: &'a str,
}

fn main() {
    let strings = Struct {
        first: "no newline",
        second: "trailing newline\n",
        third: "two\nlines\n",
        fourth: "no\ntrailing\nnewline",
    };
    print!("{}", serde_yaml::to_string(&strings).unwrap());
}
```

```yaml
first: no newline
second: |
  trailing newline
third: |
  two
  lines
fourth: |-
  no
  trailing
  newline
```
