### ISSUE TITLE
Deserializing to `Value` silently ignores duplicate keys

### ISSUE THREAD

**Issue by stevenengler** [dtolnay/serde-yaml#299]
The YAML spec disallows duplicate keys:

> The content of a mapping node is an unordered set of key: value node pairs, with the restriction that each of the keys is unique.

When deserializing to a custom serde-derive struct we can use `#[serde(with = "serde_with::rust::maps_duplicate_key_is_error")]` to prevent duplicate keys. But if we want to deserialize to a `serde_yaml::Value`, serde-yaml's mappings will ignore duplicate keys. Is there any way to achieve the same behaviour when deserializing to a `serde_yaml::Value`?

The reason for wanting to deserialize to a `serde_yaml::Value` is that I would like to take advantage of the new `apply_merge()` feature. So what I'm doing is:

```rust
let mut config: serde_yaml::Value = serde_yaml::from_reader(file).unwrap();
config.apply_merge().unwrap();
let config: MyConfig = serde_yaml::from_value(config).unwrap();
```

**Comment by dtolnay** [comment]
Fixed in 0.9.4. I didn't realize this was specified as disallowed by the YAML spec.

**Comment by stevenengler** [comment]
Wow that was quick, thanks!

**Comment by NigelThorpe** [comment]
Except that the majority of YAML parsers out there allow duplicate keys, and take a "last key wins" philosophy. See e.g. https://github.com/chyh1990/yaml-rust/issues/19

I've got some things which were considered valid before but now aren't. I'd argue this was a breaking change, despite the YAML spec.
