### ISSUE TITLE
serde-yaml 0.5.0 is harder to test because keys are no longer alphabetical

### ISSUE THREAD

**Issue by emk** [dtolnay/serde-yaml#30]
Thank you for serde_yaml! We're using it almost everywhere in [cage](https://github.com/faradayio/cage) now, and it's great.

I tried upgrading to 0.5.0 this morning, however, and a lot of my YAML-related test suites started failing. These test suites often take the form of round-trip YAML parsing and serialization tests:

```rust
macro_rules! assert_roundtrip {
    ( $ty:ty, $yaml:expr ) => {
        {
            let yaml: &str = $yaml;
            let data: $ty = serde_yaml::from_str(&yaml).unwrap();
            let yaml2 = serde_yaml::to_string(&data).unwrap();
            assert_eq!(normalize_yaml(yaml), normalize_yaml(&yaml2));
        }
    }
}

#[test]
fn extends_can_be_roundtripped() {
    let yaml = r#"---
"file": "bar/docker-compose.yml"
"service": "foo"
"#;
    assert_roundtrip!(Extends, yaml);
}
```

These test cases fail because they no longer output YAML keys in an easily predictable order:

```
---- v2::extends_can_be_roundtripped stdout ----
	thread 'v2::extends_can_be_roundtripped' panicked at 'assertion failed: `(left == right)` (left: `"---\n\"file\": \"bar/docker-compose.yml\"\n\"service\": \"foo\""`, right: `"---\n\"service\": \"foo\"\n\"file\": \"bar/docker-compose.yml\""`)', src/v2/extends.in.rs:53
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

If keys are being output in unstable orders, this also means that we won't be able to usefully diff the YAML files output by `cage export`, which is helpful if we need to debug a configuration change to our production servers.

Would you expect the new order of serialized YAML keys to be predictable from run to run?

Thank you very much for maintaining serde_yaml, and for any advice you can provide!

**Comment by dtolnay** [comment]
I definitely should have mentioned this in the release notes - added now. The keys will be in the same order as they appear in the struct.

I think this is a better default than sorting everything. Often there is a particular order that makes sense in the source code, and the same order most likely makes sense in YAML too. It also matches the behavior of serde_json as well as the equivalent Go code.

Are you going to need a way to revert to the previous sorting behavior and if so, rather than sorting in serde_yaml how would you feel about a container attribute like `#[serde(serialize_sorted)]` to sort at compile time?

```go
package main

import (
	"fmt"
	"gopkg.in/yaml.v2"
)

const y = `
"file": "bar/docker-compose.yml"
"service": "foo"
`

type Extends struct {
	Service string
	File    string
}

func main() {
	var data Extends
	err := yaml.Unmarshal([]byte(y), &data)
	if err != nil {
		panic(err)
	}

	y2, err := yaml.Marshal(data)
	if err != nil {
		panic(err)
	}

	// service: foo
	// file: bar/docker-compose.yml
	fmt.Print(string(y2))
}
```

**Comment by emk** [comment]
Actually, source order is _great_. As long as the order is consistent from
run to run, we can maintain testability and diff-ability. There's
definitely no need to support alphabetic order.

Thank you very much!
