### ISSUE TITLE
Structs not being deserialized properly

### ISSUE THREAD

**Issue by IgnisDa** [dtolnay/serde-yaml#302]
Awesome library! Thanks!

I think I have found a bug:

I have a struct which uses Yaml tags. Here is when I print the original yaml string:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/60938164/182909836-6bb5de6e-e40b-4eae-8d5e-be3e147cb447.png">

Here is what happens when I de-serialize the same struct:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/60938164/182909973-77063168-dd6e-4ee6-89c6-fbf1b9b5499f.png">

As you can see `!ClassValidator` tag is lost when de-serializing.

**Comment by IgnisDa** [comment]
Basically it is not able to deserialize this value correctly: 
![Uploading image.png…]()

**Comment by dtolnay** [comment]
Thanks! Indeed this was a bug. I've published a fix in serde_yaml 0.9.6.
