### ISSUE TITLE
Option to remove quotes

### ISSUE THREAD

**Issue by antoyo** [dtolnay/serde-yaml#31]
Hello.
Is there an option to remove the quotes from the yaml output?
[As far as I know](https://en.wikipedia.org/wiki/YAML#Syntax), quotes are not really used in YAML:

> Strings (scalars) are ordinarily unquoted, but may be enclosed in double-quotes ("), or single-quotes (').

Thanks.

**Comment by dtolnay** [comment]
Totally agree, it would be better not to quote anything unless it needs to be quoted. The quoting behavior comes from yaml-rust which is a dependency of this crate. Short of reimplementing a YAML emitter, there is nothing we can do in serde_yaml to fix it so I am closing this issue. The ticket you want to watch is https://github.com/chyh1990/yaml-rust/issues/26.
