### ISSUE TITLE
Omit empty Vec

### ISSUE THREAD

**Issue by antoyo** [dtolnay/serde-yaml#32]
Hello.
It would be nice to be able to omit empty vectors in the output and also being able to parse an input with a missing field to the empty vector.

For instance, the following code:
```rust
    let point = Point { x: 1.0, y: 2.0, children: vec![] };
```
could produce:
```
---
"x": 1
"y": 2
```
instead of:
```
---
"x": 1
"y": 2
"children": []
```

Thanks.

**Comment by dtolnay** [comment]
Serde supports this kind of fine-tuning of the serialization and deserialization using [attributes](https://serde.rs/attributes.html). I think this does what you want:

```rust
#[derive(Serialize, Deserialize)]
struct Point {
    x: f64,
    y: f64,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    children: Vec<u8>,
}
```

- The `skip_serializing_if` attribute specifies a function that is called to decide whether to serialize the current value of the field.
- The `default` attribute says to use the `Default::default()` value of the field if it is not present in the input.

**Comment by antoyo** [comment]
Oh, I did not know that.
Thank you so much.
