### ISSUE TITLE
Serialize None to empty string instead of null

### ISSUE THREAD

**Issue by a-0-dev** [dtolnay/serde-yaml#320]
Serializing an `Option<T>` which is `None` will make it show up as `null` in yaml.
Since deserializing works without the value in the yaml (no-mention is correctly deserialized to `None`) it would be nice if one could set the option to serialize `None` to an empty string in reverse. In my use case, more concise serialization would be very nice.

I could imagine this as different `derive` or as an option you pass to the `serde_yaml::to_string(...)` , but any implementation would of course be enough for me.

**Comment by jonasbb** [comment]
[`serde_with::NoneAsEmptyString`](https://docs.rs/serde_with/latest/serde_with/struct.NoneAsEmptyString.html) provides a serialization format agnostic way to translate between `None` and `""`.
```rust
#[serde_as(as = "serde_with::NoneAsEmptyString")]
tags: Option<String>,
```

You can also omit the `None` values from the serialized format, to make it more concise. You can put this attribute on the `Option` fields `#[serde(skip_serializing_if = "Option::is_none")]`. If you have many such fields, you might also be interested in the [`#[serde_with::skip_serializing_none]`](https://docs.rs/serde_with/latest/serde_with/attr.skip_serializing_none.html) macro, which automates this.

**Comment by a-0-dev** [comment]
That's what I was looking for, thanks!
