### ISSUE TITLE
Version 0.5.0 cannot be used with `clap` because it enables a non-"additive" feature of `yaml-rust` and breaks the API

### ISSUE THREAD

**Issue by emk** [dtolnay/serde-yaml#33]
The details are available here: https://github.com/kbknapp/clap-rs/issues/747

The basic issue is that `serde-yaml` turns on `yaml-rust`'s `preserve_order` feature, which changes the API of `yaml-rust` in a breaking fashion, and makes it impossible to use certain third-party crates.

**Comment by emk** [comment]
The underlying issue with `yaml-rust` is discussed in more detail here: https://github.com/chyh1990/yaml-rust/issues/44

In light of the fact that enabling this option breaks API compatibility for other users of `yaml-rust`, it might be best to just leave it disabled until a solution is found at the `yaml-rust` level.

**Comment by kbknapp** [comment]
The best outcome (for me at least) is to provide the option to *not* use `preserve_order` with `yaml-rust` since changing clap's API to match the `preserve_order` would be a breaking change. I'll be standing by for suggestions and comments though.

**Comment by dtolnay** [comment]
As of 0.9, serde-yaml no longer depends on yaml-rust.
