### ISSUE TITLE
deny_unknown_fields on empty struct

### ISSUE THREAD

**Issue by ibigbug** [dtolnay/serde-yaml#331]
deny_unknown_fields on empty struct seems broken:

```rust
use serde::Deserialize;

#[derive(Deserialize, Debug)]
struct Request {
    pub a: bool,
    
}

#[derive(Deserialize, Debug)]
struct Request2;



fn main() {
    let y = r#"
    m:
    a: true
    "#;

    let requests: Request = serde_yaml::from_str(y).unwrap();
    println!("{:?}", requests);
    
      let yy = r#"
    m:
    "#;
    
    let requests2: Request2 = serde_yaml::from_str(yy).unwrap();
    println!("{:?}", requests2);
    
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=408b3e98e302aae032a799b3cf9335d8

possibly similar to #304

**Comment by dtolnay** [comment]
It doesn't look like you are using deny_unknown_fields in the code you pasted. Can you clarify the issue?

**Comment by ibigbug** [comment]
@dtolnay the `deny_unknown_fields` is by default `false`, and can only be turned on by setting the attribute, so it should allow unknown fields, for example in `Request` the field `m` is ignored by default.

but for `Request2` is throwing error, instead of ignoring the field `m`.

**Comment by dtolnay** [comment]
`struct Request2;` is not an empty struct, it is a unit struct. The field `m` isn't the issue, it's that the YAML contains a map and unit structs are not represented as maps. This is consistent with how `struct Request();` (a tuple struct) would also not be valid to deserialize from a map.

An empty struct (braced struct with no fields) would be written `struct Request2 {}` and will deserialize from a map, ignore unknown field unless annotated `serde(deny_unknown_fields)`.

The behavior of serde_yaml here matches the behavior of serde_json, neither `{}` nor `{"m":null}` is valid to deserialize as a unit struct in JSON either.

**Comment by ibigbug** [comment]
I see. good to know.

putting `struct Request2 {}` is working as expected. thank you!
