### ISSUE TITLE
Emoji serialized to Unicode escape sequence

### ISSUE THREAD

**Issue by inflation** [dtolnay/serde-yaml#356]
I have some cursed configs with emojis (don't ask me why), and need to patch those files without touching other parts. It's all good until the last serialize part. Those emojis are converted to Unicode escape sequence:

```rust
let test = '🎉';
println!("{}", serde_yaml::to_string(&test).unwrap());
```
Output: `"\U0001F389"`

Although, it's technically equivalent but not very human-readable. PyYAML has an option `allow_unicode` for `dump` to keep them. I'd love to see a similar option for `serde-yaml`.

**Comment by dtolnay** [comment]
Fixed in serde_yaml 0.9.18.
