### ISSUE TITLE
this serializer isn't working with serde_yaml but it does work with serde_json

### ISSUE THREAD

**Issue by radix** [dtolnay/serde-yaml#37]
I may be doing something wrong, but I wrote this serializer today and tried it with both JSON and YAML.

```rust
#[derive(Clone, Eq, PartialEq, Debug)]
pub struct NonEmptyWithCursor<T> {
    most: Vec<T>,
    head: T,
    cursor: usize,
}

impl<T> Serialize for NonEmptyWithCursor<T>
    where T: Serialize
{
    fn serialize<S>(&self, serializer: &mut S) -> Result<(), S::Error>
        where S: Serializer
    {
        let mut state = serializer.serialize_map(Some(2))?;
        serializer.serialize_map_key(&mut state, "cursor")?;
        serializer.serialize_map_value(&mut state, self.cursor)?;
        serializer.serialize_map_key(&mut state, "data")?;
        let mut seqstate = serializer.serialize_seq(Some(self.len()))?;
        serializer.serialize_seq_elt(&mut seqstate, &self.head)?;
        for elt in self.most.iter() {
            serializer.serialize_seq_elt(&mut seqstate, elt)?;
        }
        serializer.serialize_seq_end(seqstate)?;
        serializer.serialize_map_end(state)
    }
}
```

With JSON output, it emits something like this: `{"cursor": 0, "data": [...]}`. But with YAML output, it emits the `cursor: 0` but not any data.

Is there something else I should be doing to emit a sequence as a value associated with a key? Or is this actually a bug in serde_yaml?

**Comment by radix** [comment]
FWIW I've also now tested this with TOML and it is also serializing correctly with that.

**Comment by radix** [comment]
It looks like serde-yaml's serializer works very differently than other serializer's for serde. It seems to assume that only one value will be serialized per serializer, where each function that serializes a value just replaces `self.doc` instead of continuing to write out to a larger structure. I guess fixing this bug is going to be a significant rewrite of the serializer code.

**Comment by dtolnay** [comment]
The `Serialize` trait's responsibility is to make exactly one primitive Serializer call (serialize_u8, serialize_str etc) or exactly one chain of begin/elements/end Serializer calls. We have been thinking about ways to enforce this in the type system to prevent impls like the one you have https://github.com/serde-rs/serde/issues/651.

In general serializing a value in a map may require the Serializer to have access to the MapState object (`state` in your code). TOML and JSON do not use the MapState for serialize_map_value but YAML does, which explains why they behave differently. Your code is not providing the MapState anywhere for the second map value.

To do this correctly, create a newtype wrapper `struct Data<'a, T>(&'a NonEmptyWithCursor<T>)` and implement Serialize for that to do what your second map value is doing, then use:

```rust
serializer.serialize_map_value(&mut state, Data(self))?;
```

**Comment by radix** [comment]
@dtolnay I see! Thanks very much for the explanation; that worked.
