### ISSUE TITLE
Recognizing more boolean representations

### ISSUE THREAD

**Issue by jonathan-s** [dtolnay/serde-yaml#379]
I'm looking at this PR https://github.com/dtolnay/serde-yaml/pull/330/files and see that you've explicitly chosen to represent some values such as `Y` etc as strings rather than booleans. 

According to the yaml spec https://yaml.org/type/bool.html these should be considered booleans. Would you be amenable to accept a change in this behaviour? Most other (all that I know, except this one) yaml parsers do in fact convert these values to boolean values.

**Comment by dtolnay** [comment]
The page you linked is not part of the YAML spec.

**Comment by jonathan-s** [comment]
This link here > https://yaml.org/spec/1.1/#id864510 should be part of the spec as far as I understand. 

In that paragraph it's written

> YAML allows [scalar content](https://yaml.org/spec/1.1/#scalar/information%20model) to be [presented](https://yaml.org/spec/1.1/#present/) in several formats. For example, the boolean “true” might also be written as “yes”. [Tags](https://yaml.org/spec/1.1/#tag/information%20model) must specify a mechanism for converting any formatted [scalar content](https://yaml.org/spec/1.1/#scalar/information%20model) to a [canonical form](https://yaml.org/spec/1.1/#canonical%20form/) for use in [equality](https://yaml.org/spec/1.1/#equality/) testing. Like [node style](https://yaml.org/spec/1.1/#style/), the format is a [presentation detail](https://yaml.org/spec/1.1/#presentation%20detail/) and is not reflected in the [serialization tree](https://yaml.org/spec/1.1/#serialization/) and [representation graph](https://yaml.org/spec/1.1/#representation/).

Reflecting that `yes` is part of what should be represented as a boolean. 

The section on [tags](https://yaml.org/spec/1.1/#id858600). Also links to the link I mentioned first. 

> The repository includes additional types such as [“null”](https://yaml.org/type/null.html), [“bool”](https://yaml.org/type/bool.html), [“set”](https://yaml.org/type/set.html) and others.

**Comment by dtolnay** [comment]
That new link is at least 14 years out of date.

As far as I am able to discern, here is the spec that defines what values to interpret implicitly as bool: https://yaml.org/spec/1.2.2/#1032-tag-resolution. This was linked in the summary of my PR that you linked to at the top.

**Comment by jonathan-s** [comment]
I stand corrected. Thank you for taking the time to reply.
