### ISSUE TITLE
Fetaure Request: `yaml!()` macro similar to `serde_json::json!({})`

### ISSUE THREAD

**Issue by Fishrock123** [dtolnay/serde-yaml#385]
It would be great for purposes of templating and constructing yaml configs for other programs to have a nice way to declare lots of nested yaml in source code, similar to [`serde_json`'s `json!({})` macro](https://docs.rs/serde_json/1.0.104/serde_json/macro.json.html).

Of course we all know this sounds much easier than it is to do. It's a big ask but I hope the Rust community can get it some day.

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate.

**Comment by Fishrock123** [comment]
So, best would be to have separate crate i.e. a theoretical `serde_yaml_macro` to house this functionality?
