### ISSUE TITLE
Long Map keys bug

### ISSUE THREAD

**Issue by perryqh** [dtolnay/serde-yaml#407]
Is there a max line length set somewhere? I'm noticing that if a map `key` is greater than 128 characters, unexpected characters are prepended and appended to the key.

Here's a failing test: https://github.com/perryqh/serde-yaml/commit/401a1f246bd9835239056479ed7f65d815980a15.

I'm happy to fix this if you point me in the right direction.

**Comment by dtolnay** [comment]
I think that is probably intended behavior. That is valid syntax for a map in YAML.

**Comment by perryqh** [comment]
Is the prepended `?` character valid YAML?

**Comment by dtolnay** [comment]
Yes.
