### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/serde-yaml#41]
I published 0.6.0-rc1 with support for serde 0.9 and a rewritten parser that shows line and column for errors. Some examples from the test suite:

> invalid value: string "str", expected an integer at line 2 column 7

> missing field \`w\` at line 2 column 2

> invalid length 2, expected a tuple of size 3 at line 2 column 1

I don't have any projects myself that use serde_yaml so @sfackler or @jwilm would you be interested in updating one of your projects to rc1 as a sanity check?

**Comment by sfackler** [comment]
log4rs is also waiting on https://github.com/alexcrichton/toml-rs/issues/135, and another thing is waiting on erased-serde, but I can start on the log4rs migration without toml to check it out.

**Comment by sfackler** [comment]
No real drama on the log4rs upgrade: https://github.com/sfackler/log4rs/commit/af54f15e0aeff9a8550f19ced73b8b39aa493353

**Comment by dtolnay** [comment]
https://github.com/dtolnay/serde-yaml/releases/tag/0.6.0

**Comment by jwilm** [comment]
Going to be doing this later today

**Comment by jwilm** [comment]
https://github.com/jwilm/alacritty/pull/371

No issues with the yaml update. Had a bunch of changes due to serde 0.9, though, but that's not what this is about :P.
