### ISSUE TITLE
`DeserializeSeed` support

### ISSUE THREAD

**Issue by cjhowe** [dtolnay/serde-yaml#48]
Sometimes, it's necessary for a type to only implement `DeserializeSeed`, and not `Deserialize`. `serde_yaml` should support this use case, especially with the functions related to `from_str`. I think the type should look something like this:

```
fn from_str_seed<T>(seed: T, s: &str) -> Result<T::Value>
    where T: DeserializeSeed
```

**Comment by dtolnay** [comment]
As we discussed in https://github.com/serde-rs/json/issues/282 - I think this is better addressed by https://github.com/dtolnay/serde-yaml/issues/44. Something like:

```rust
seed.deserialize(&mut serde_yaml::Deserializer::from_str(s))
```
