### ISSUE TITLE
Remove public dependency on yaml_rust

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/serde-yaml#51]
The public dependency right now is these three impls:

```rust
impl From<yaml_rust::Yaml> for serde_yaml::Value { /* ... */ }
impl From<yaml_rust::emitter::EmitError> for serde_yaml::Error { /* ... */ }
impl From<yaml_rust::scanner::ScanError> for serde_yaml::Error { /* ... */ }
```

Making the dependency entirely private would allow us to freely update yaml_rust versions, switch to a yaml_rust fork if necessary, and most importantly release serde_yaml 1.0 along with serde 1.0 before yaml_rust reaches 1.0.

**Comment by mathstuf** [comment]
Does Cargo even have the knowledge of a split public/private dependency set yet? Or is it just a more "it is less likely to break" situation?

**Comment by dtolnay** [comment]
Cargo does not enforce it. But 1.0 means the public API will not need to change in breaking ways in the near future, and having pre-1.0 types in the public API violates that.

**Comment by dtolnay** [comment]
Done in c05984767f4a76d445ac55a8e2b7d0b33025d8be and 60fafdabccec298e53a323d79cfc579d27b50f1d.
