### ISSUE TITLE
Remove from_iter

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/serde-yaml#61]
This was added to serde_json years ago and is superseded by from_reader.

**Comment by drusellers** [comment]
So, I need to remove `FromIterator` from `Mapping` and `Value` ?

I see:
- https://github.com/dtolnay/serde-yaml/blob/master/src/value/from.rs#L259
- https://github.com/dtolnay/serde-yaml/blob/master/src/mapping.rs#L125

and it sounds like I should implement `from_reader` in its place?

**Comment by dtolnay** [comment]
Oh I already did this in d04bcd67eb5a5c642b9a4639058db1d4f8c9c297 :rofl:. Sorry, do #60.
