### ISSUE TITLE
Release Package to track Serde 1.0

### ISSUE THREAD

**Issue by drusellers** [dtolnay/serde-yaml#63]
I see that you have already started tracking 1.0 of `serde` which is awesome. I also pulled down a copy of the code and see that you are tracking the master branch of `serde`. All tests pass and the project successfully compiles.

The `README.md` still states `serde="0.9"` and https://crates.io/crates/serde_yaml shows `^0.9.2`.  How can I help release a new `serde_yaml` package that reports a dependency of `serde=1.0.0` or equiv.

Happy to help make it happen.

**Comment by dtolnay** [comment]
Thanks @drusellers! There are two more breaking changes I need to fit in before releasing. Would you be able to help me out with PRs for #61 and #61 as well as bumping to the released version of serde?

**Comment by dtolnay** [comment]
I released serde_yaml 0.7.0 with support Serde 1.0.
