### ISSUE TITLE
Fork yaml-rust

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/serde-yaml#67]
The yaml-rust maintainer has been very slow to respond to pull requests and it is harmful to this library. It's time for a fork.

**Comment by killercup** [comment]
Do you 'just' want to actually fork the repo or rewrite/reuse (parts of) the lib and integrate it into this crate? Doing the latter will be more work but will probably make the code easier to maintain in the long term.

**Comment by dtolnay** [comment]
The yaml-rust guy added me as a collaborator so we are going to be making some changes. :sunglasses:

I do not want to maintain a YAML parser tightly coupled to serde-yaml. The YAML spec is ridiculous.
