### ISSUE TITLE
Run tests with serde_macros on stable and beta

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/serde-yaml#7]
#6 added Travis builds for stable and beta but without running tests, because the tests rely on serde_macros. Look into how [serde-rs/json](https://github.com/serde-rs/json) run their tests.

**Comment by calebmer** [comment]
+1 for stable testing

**Comment by dtolnay** [comment]
All set! [Here is what gets run:](https://github.com/dtolnay/serde-yaml/blob/690b0feadb567fdc67cec12ff40f4752c0379784/scripts/build.sh#L33-L41)

```bash
if [ "$TRAVIS_RUST_VERSION" = nightly ]; then
    build_with_clippy
    test_with_macros
    test_with_syntex
    generate_doc
else
    build_without_clippy
    test_with_syntex
fi
```
