### ISSUE TITLE
Can't use with borrowed values in a struct

### ISSUE THREAD

**Issue by kbknapp** [dtolnay/serde-yaml#94]
Myself and @savish are working on porting `clap` to use `serde` for all the serialization and deserialization in clap v3. Currently, YAML is the most popular format to deserialize from for `clap` (because it's the only supported way in v2 :stuck_out_tongue_winking_eye: ). So we started with a YAML test.

When trying to derive `Deserialize` for `clap::App` we run into the error about the `'de` lifetime:

```
15 |     let app: App = serde_yaml::from_str(&yml).unwrap();
   |                         ^^^^^^^^^^^^^^^^^^^^
   |
   = note: required because of the requirements on the impl of `for<'de> _IMPL_DESERIALIZE_FOR_Point::_serde::Deserialize<'de>` for `App<'_,'_>`
   = note: required because of the requirements on the impl of `_IMPL_DESERIALIZE_FOR_Point::_serde::de::DeserializeOwned` for `App<'_,'_>`
   = note: required by `serde_yaml::from_str`
```

However, if we do the *exact* same test with `serde_json` (using a JSON document of course) everything works. So no changes to the `clap::App` struct, just using `serde_json` instead of `serde_yaml` it all works.

## Version of `serde_yaml`

0.7.5

May be related to #85?

**Comment by dtolnay** [comment]
[`serde_json::from_str`](https://docs.rs/serde_json/1.0.20/serde_json/fn.from_str.html) and [`serde_yaml::from_str`](https://docs.rs/serde_yaml/0.7.5/serde_yaml/fn.from_str.html) have different signatures. YAML only supports deserializing owned data for now. I am not planning to work on this myself and I think it would be a fairly large amount of work, but I would happily accept a PR to support deserializing borrowed data.

**Comment by turboladen** [comment]
FWIW, I'm running into this as well. I've got a bit of a specialized port of [Rails/Ruby's I18n](https://guides.rubyonrails.org/i18n.html) YAML stuff for translating some things for a private crate. Since the data I'm after is really just a static lookup table (that's deserialized from YAML), I was hoping to generate a static struct containing the translations. Just thought I'd leave my use case here in case it helps give some clout to the ticket.

**Comment by dtolnay** [comment]
I posted a request for implementation for a new backend: https://github.com/dtolnay/request-for-implementation/issues/9.

**Comment by dtolnay** [comment]
As of 0.9, serde-yaml uses a new YAML backend, which supports this.
