### ISSUE TITLE
implement From<io::Error> for serde_yaml::Error

### ISSUE THREAD

**Issue by droundy** [dtolnay/serde-yaml#97]
Would it be acceptable to implement Fromio::Error for serde_yaml::Error? This would make it easier to combine serde with reading or writing of values, something like:

fn read(value: f6, p: &Path) -> Result<f64, serde::Error> {
        let mut f = ::std::fs::File::create(p)?;
        serde_yaml::to_writer(&f, value)
}
I know there are crates to enable combining of error types, but for my use case that seems excessive, when a simple impl in serde would remove the need for such.

**Comment by dtolnay** [comment]
I would prefer not to support this. Only serde_yaml is intended to be able to create serde_yaml errors. Since serde_yaml does not create files, it would be surprising to have a serde_yaml error saying it failed to create a file. Thanks anyway!
